### ISSUE TITLE
dark/light mode cycling not working?

### ISSUE THREAD

**Issue by mmcnl** [ErikBoesen/BWNT#21]
![image](https://user-images.githubusercontent.com/1498727/57564622-a349f380-7363-11e9-937f-8faaa7a023f2.png)
From looking at the code, since the time was later than 20:00, I was expecting/hoping the background would be dark. Am I misunderstanding how this feature works?

**Comment by ErikBoesen** [comment]
I cannot reproduce this.

**Comment by ErikBoesen** [comment]
You may want to clear your cache, that might help.
